replicaCount: 1
namespace: hello-world

image:
  repository: juniper620/demo-aks
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

containerPort: 5000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
