apiVersion: v1
kind: Service
metadata:
  name: flash-book-api-service
spec:
  selector:
    app: flash-book-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # Make sure the target port matches the container's exposed port
  type: LoadBalancer