name: Helm Deployment to AKS

on:
  workflow_call:

jobs:
  helm-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure credentials
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group my-resource-group --name my-aks --overwrite-existing

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install application ./helloworld \
            --namespace hello-world \
            --create-namespace \
            -f ./helloworld/values.yaml
