name: Master Deployment Pipeline

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  approval:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    environment:
      name: devops
    steps:
      - name: Awaiting manual approval
        run: echo "Manual approval granted via environment 'devops'"

  run-iac:
    needs: approval
    uses: ./.github/workflows/iac.yaml
    secrets: inherit

  run-helm:
    needs: run-iac
    uses: ./.github/workflows/application.yaml
    secrets: inherit
