name: Master Deployment Pipeline

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  approval:
    runs-on: ubuntu-latest
    environment:
      name: devops
    steps:
      - name: Awaiting manual approval
        run: echo "Manual approval granted via environment 'devops'"

  run-iac:
    needs: approval
    uses: ./.github/workflows/iac.yml
    secrets: inherit

  run-helm:
    needs: run-iac
    uses: ./.github/workflows/helm.yml
    secrets: inherit
